export const ROUTER = {
  UNAUTHORIZE: '/unauthorize',
  BASE: '/',
  LOGIN: '/login',
  TEACHER: '/teacher',
  TEACHER_DETAILS: '/teacher/:id',
  ROOM: '/room',
  ROOM_DETAILS: '/room/:id',
  FACILITY: '/facility',
  USER: '/user',
  COURSE: '/course',
  CREATE_COURSE: '/create-course',
  UPDATE_COURSE: '/course/:id',
  NEWS: '/news',
  NEWS_DETAILS: '/news/:id',
  STUDENT: '/student',
  STUDENT_DETAILS: '/student/:id',
  FEEDBACK: '/feedback',
  NOTIFICATION: '/notification'
};
